### ISSUE TITLE
Some errors with config options handling

### ISSUE THREAD

**Issue by Sokolmish** [astibal/smithproxy#32]
Hello. I get a segfault when I use `--config-check-only` option. It seems like that it's caused by using `Log::get()` [here](https://github.com/astibal/smithproxy/blob/master/src/main.cpp#L374), before calling `Log::init()`.

Also, if I use short option `-c` to specify config file, i will get the following error.
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```
It seems like there should be a `:` sign after the `c` in the [short options list](https://github.com/astibal/smithproxy/blob/master/src/main.cpp#L359) to indicate, that this option has a mandatory argument.

**Comment by astibal** [comment]
I will look into it ,thanks for reporting it.

**Comment by astibal** [comment]
I will be releasing `0.9.31` soon.

**Comment by Sokolmish** [comment]
I didn't test it, but I guess that options `-i` and `-t` also should have a colon after them in short options string, since they requires arguments too.

**Comment by astibal** [comment]
Yes, sometimes faster isn't better. ;)

**Comment by Sokolmish** [comment]
Hi. It's me again. `sx_ctl start` stop working because it still [uses](https://github.com/astibal/smithproxy/blob/e030b4a2df57e8ac9cb2e4e784ba23d1d29248d9/src/infra/smithdog.py#L395) removed `--tenant-index` option.
Also, this option is still present in the [long options list](https://github.com/astibal/smithproxy/blob/e030b4a2df57e8ac9cb2e4e784ba23d1d29248d9/src/main.cpp#L334).

**Comment by astibal** [comment]
Thanks, indeed. 
Hmm, I am not using `sx_ctl` anymore anywhere on my testing environment.  I will fix it. Please don't close it until release, as there are certainly other corners which could be affected by this.

**Comment by astibal** [comment]
Tested  on ubuntu 22.04, `sx_ctl`, `sx_network` and `sx_cli` all work after `--tenant-index` wipe. 
[Log: sx_ctl_network_cli.txt](https://github.com/astibal/smithproxy/files/10146277/sx_ctl_network_cli.txt)

**Comment by astibal** [comment]
If there is yet another issue, please reopen. It seems alright, closing now.
